local M = {
  "lukas-reineke/indent-blankline.nvim",
  event = "BufReadPre",
  config = {
    indentLine_enabled = 1,
    char = "▏",
    buftype_exclude = {
      "terminal",
      "nofile",
      "terminal",
    },
    filetype_exclude = {
      "help",
      "terminal",
      "alpha",
      "packer",
      "lspinfo",
      "TelescopePrompt",
      "TelescopeResults",
      "nvchad_cheatsheet",
      "lsp-installer",
      "",
    },
    char = "▏",
    use_treesitter_scope = false,
    show_trailing_blankline_indent = false,
    show_current_context = true,
    context_patterns = {
      "class",
      "return",
      "function",
      "method",
      "^if",
      "^while",
      "jsx_element",
      "^for",
      "^object",
      "^table",
      "block",
      "arguments",
      "if_statement",
      "else_clause",
      "jsx_element",
      "jsx_self_closing_element",
      "try_statement",
      "catch_clause",
      "import_statement",
      "operation_type",
    },
  },
}

return M
